// MotivationalQuotes.js
const quotes = [
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "The only way to do great work is to love what you do. – Steve Jobs",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "It does not matter how slowly you go as long as you do not stop. – Confucius",
  "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
  "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
  "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
  "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
  "Act as if what you do makes a difference. It does. – William James",
  "Success doesn’t come from what you do occasionally, but from what you do consistently. – Marie Forleo",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
  "Your limitation—it's only your imagination. – Unknown",
  "Push yourself, because no one else is going to do it for you. – Unknown",
  "Great things never come from comfort zones. – Unknown",
  "Dream it. Wish it. Do it. – Unknown",
  "Success doesn’t just find you. You have to go out and get it. – Unknown",
  "The harder you work for something, the greater you’ll feel when you achieve it. – Unknown",
  "Dream bigger. Do bigger. – Unknown",
  "Don’t stop when you’re tired. Stop when you’re done. – Unknown",
  "Wake up with determination. Go to bed with satisfaction. – Unknown",
  "Do something today that your future self will thank you for. – Unknown",
  "Little things make big days. – Unknown",
  "It’s going to be hard, but hard does not mean impossible. – Unknown",
  "Don’t wait for opportunity. Create it. – Unknown",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths. – Unknown",
  "The key to success is to focus on goals, not obstacles. – Unknown",
  "Dream it. Believe it. Build it. – Unknown",
  "Motivation is what gets you started. Habit is what keeps you going. – Jim Ryun",
  "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
  "The secret of getting ahead is getting started. – Mark Twain",
  "Success is not the absence of obstacles, but the courage to push through. – Unknown",
  "Every champion was once a contender that refused to give up. – Rocky Balboa",
  "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
  "Don’t limit your challenges. Challenge your limits. – Unknown",
  "Opportunities don’t happen. You create them. – Chris Grosser",
  "It always seems impossible until it’s done. – Nelson Mandela",
  "Success is liking yourself, liking what you do, and liking how you do it. – Maya Angelou",
  "Aim for the moon. If you miss, you may hit a star. – W. Clement Stone",
  "If you can dream it, you can do it. – Walt Disney",
  "The difference between who you are and who you want to be is what you do. – Unknown",
  "A journey of a thousand miles begins with a single step. – Lao Tzu",
  "Don’t wait. The time will never be just right. – Napoleon Hill",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
  "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
  "You get what you give. – Jennifer Lopez",
  "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
  "The harder the battle, the sweeter the victory. – Les Brown",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. – Joshua J. Marine",
  "You don’t have to see the whole staircase, just take the first step. – Martin Luther King Jr.",
  "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
  "Turn your wounds into wisdom. – Oprah Winfrey",
  "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
  "The best way to predict the future is to create it. – Peter Drucker",
  "You miss 100% of the shots you don’t take. – Wayne Gretzky",
  "I am not a product of my circumstances. I am a product of my decisions. – Stephen Covey",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. – Nelson Mandela",
  "Life isn’t about finding yourself. Life is about creating yourself. – George Bernard Shaw",
  "Do what you can, with what you have, where you are. – Theodore Roosevelt",
  "Strive not to be a success, but rather to be of value. – Albert Einstein",
  "The mind is everything. What you think you become. – Buddha",
  "Either you run the day, or the day runs you. – Jim Rohn",
  "Whether you think you can or you think you can’t, you’re right. – Henry Ford",
  "The best revenge is massive success. – Frank Sinatra",
  "Winning isn’t everything, but wanting to win is. – Vince Lombardi",
  "I’ve failed over and over and over again in my life. And that is why I succeed. – Michael Jordan",
  "If you’re going through hell, keep going. – Winston Churchill",
  "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
  "Go confidently in the direction of your dreams. Live the life you have imagined. – Henry David Thoreau",
  "When you have a dream, you’ve got to grab it and never let go. – Carol Burnett",
  "Nothing is impossible. The word itself says ‘I’m possible!’ – Audrey Hepburn",
  "There is nothing impossible to they who will try. – Alexander the Great",
  "The bad news is time flies. The good news is you’re the pilot. – Michael Altshuler",
  "Life has got all those twists and turns. You’ve got to hold on tight and off you go. – Nicole Kidman",
  "Keep your face always toward the sunshine, and shadows will fall behind you. – Walt Whitman",
  "Be courageous. Challenge orthodoxy. Stand up for what you believe in. – Unknown",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston Churchill",
  "You define your own life. Don’t let other people write your script. – Oprah Winfrey",
  "You are never too old to set another goal or to dream a new dream. – Les Brown",
  "At any given moment you have the power to say: this is not how the story is going to end. – Unknown",
  "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
  "The only limits in life are the ones you make. – Unknown",
  "You must do the thing you think you cannot do. – Eleanor Roosevelt",
  "Success isn’t always about greatness. It’s about consistency. – Dwayne Johnson",
  "The best way to get started is to quit talking and begin doing. – Walt Disney",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. – Winston Churchill",
  "Don’t let yesterday take up too much of today. – Will Rogers",
  "You learn more from failure than from success. Don’t let it stop you. Failure builds character. – Unknown",
  "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi",
  "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you. – Steve Jobs",
  "People who are crazy enough to think they can change the world, are the ones who do. – Rob Siltanen",
  "Failure will never overtake me if my determination to succeed is strong enough. – Og Mandino",
  "Entrepreneurs are great at dealing with uncertainty and also very good at minimizing risk. That’s the classic entrepreneur. – Mohnish Pabrai",
  "We may encounter many defeats but we must not be defeated. – Maya Angelou",
  "Knowing is not enough; we must apply. Wishing is not enough; we must do. – Johann Wolfgang von Goethe",
  "Imagine your life is perfect in every respect; what would it look like? – Brian Tracy",
  "We generate fears while we sit. We overcome them by action. – Dr. Henry Link",
  "Whether you think you can or think you can’t, you’re right. – Henry Ford",
  "Security is mostly a superstition. Life is either a daring adventure or nothing. – Helen Keller",
  "The man who has confidence in himself gains the confidence of others. – Hasidic Proverb",
  "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
  "Creativity is intelligence having fun. – Albert Einstein",
  "What you lack in talent can be made up with desire, hustle and giving 110% all the time. – Don Zimmer",
  "Do what you can with all you have, wherever you are. – Theodore Roosevelt",
  "Develop an ‘Attitude of Gratitude’. Say thank you to everyone you meet for everything they do for you. – Brian Tracy",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "To see what is right and not do it is a lack of courage. – Confucius"
];

export default quotes;